// flow-typed signature: 7f23ddd0d68e8f449a3b66af59eea4b2
// flow-typed version: <<STUB>>/dayjs_v^1.5.13/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dayjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dayjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dayjs/dist/dayjs.min' {
  declare module.exports: any;
}

declare module 'dayjs/rollup.config' {
  declare module.exports: any;
}

declare module 'dayjs/src/constant' {
  declare module.exports: any;
}

declare module 'dayjs/src/index' {
  declare module.exports: any;
}

declare module 'dayjs/src/utils' {
  declare module.exports: any;
}

declare module 'dayjs/test/display.test' {
  declare module.exports: any;
}

declare module 'dayjs/test/get-set.test' {
  declare module.exports: any;
}

declare module 'dayjs/test/manipulate.test' {
  declare module.exports: any;
}

declare module 'dayjs/test/parse.test' {
  declare module.exports: any;
}

declare module 'dayjs/test/query.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dayjs/dist/dayjs.min.js' {
  declare module.exports: $Exports<'dayjs/dist/dayjs.min'>;
}
declare module 'dayjs/rollup.config.js' {
  declare module.exports: $Exports<'dayjs/rollup.config'>;
}
declare module 'dayjs/src/constant.js' {
  declare module.exports: $Exports<'dayjs/src/constant'>;
}
declare module 'dayjs/src/index.js' {
  declare module.exports: $Exports<'dayjs/src/index'>;
}
declare module 'dayjs/src/utils.js' {
  declare module.exports: $Exports<'dayjs/src/utils'>;
}
declare module 'dayjs/test/display.test.js' {
  declare module.exports: $Exports<'dayjs/test/display.test'>;
}
declare module 'dayjs/test/get-set.test.js' {
  declare module.exports: $Exports<'dayjs/test/get-set.test'>;
}
declare module 'dayjs/test/manipulate.test.js' {
  declare module.exports: $Exports<'dayjs/test/manipulate.test'>;
}
declare module 'dayjs/test/parse.test.js' {
  declare module.exports: $Exports<'dayjs/test/parse.test'>;
}
declare module 'dayjs/test/query.test.js' {
  declare module.exports: $Exports<'dayjs/test/query.test'>;
}
