// flow-typed signature: 90c967e87302c3e795153332d7e7a1b2
// flow-typed version: <<STUB>>/eslint-config-tutellus_v^2.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-tutellus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-tutellus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-tutellus/func' {
  declare module.exports: any;
}

declare module 'eslint-config-tutellus/lang' {
  declare module.exports: any;
}

declare module 'eslint-config-tutellus/obj' {
  declare module.exports: any;
}

declare module 'eslint-config-tutellus/rules' {
  declare module.exports: any;
}

declare module 'eslint-config-tutellus/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-tutellus/func.js' {
  declare module.exports: $Exports<'eslint-config-tutellus/func'>;
}
declare module 'eslint-config-tutellus/index' {
  declare module.exports: $Exports<'eslint-config-tutellus'>;
}
declare module 'eslint-config-tutellus/index.js' {
  declare module.exports: $Exports<'eslint-config-tutellus'>;
}
declare module 'eslint-config-tutellus/lang.js' {
  declare module.exports: $Exports<'eslint-config-tutellus/lang'>;
}
declare module 'eslint-config-tutellus/obj.js' {
  declare module.exports: $Exports<'eslint-config-tutellus/obj'>;
}
declare module 'eslint-config-tutellus/rules.js' {
  declare module.exports: $Exports<'eslint-config-tutellus/rules'>;
}
declare module 'eslint-config-tutellus/style.js' {
  declare module.exports: $Exports<'eslint-config-tutellus/style'>;
}
