// flow-typed signature: 1457f65f416ead0518c3c0b74d6b8c88
// flow-typed version: <<STUB>>/i18next-localstorage-cache_v^1.1.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-localstorage-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-localstorage-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-localstorage-cache/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/dist/es/index' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/dist/es/utils' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache.min' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/i18nextLocalStorageCache' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/i18nextLocalStorageCache.min' {
  declare module.exports: any;
}

declare module 'i18next-localstorage-cache/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-localstorage-cache/dist/commonjs/index.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/commonjs/index'>;
}
declare module 'i18next-localstorage-cache/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/commonjs/utils'>;
}
declare module 'i18next-localstorage-cache/dist/es/index.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/es/index'>;
}
declare module 'i18next-localstorage-cache/dist/es/utils.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/es/utils'>;
}
declare module 'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache'>;
}
declare module 'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache.min.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/dist/umd/i18nextLocalStorageCache.min'>;
}
declare module 'i18next-localstorage-cache/i18nextLocalStorageCache.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/i18nextLocalStorageCache'>;
}
declare module 'i18next-localstorage-cache/i18nextLocalStorageCache.min.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/i18nextLocalStorageCache.min'>;
}
declare module 'i18next-localstorage-cache/index' {
  declare module.exports: $Exports<'i18next-localstorage-cache'>;
}
declare module 'i18next-localstorage-cache/index.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache'>;
}
declare module 'i18next-localstorage-cache/rollup.config.js' {
  declare module.exports: $Exports<'i18next-localstorage-cache/rollup.config'>;
}
