// flow-typed signature: 4efc102361dfbea0ff69169af3463c26
// flow-typed version: <<STUB>>/json-hash_v^1.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-hash/Gruntfile' {
  declare module.exports: any;
}

declare module 'json-hash/lib/browser' {
  declare module.exports: any;
}

declare module 'json-hash/lib/crypto' {
  declare module.exports: any;
}

declare module 'json-hash/lib/digest' {
  declare module.exports: any;
}

declare module 'json-hash/lib/index' {
  declare module.exports: any;
}

declare module 'json-hash/spec/spec-crypto' {
  declare module.exports: any;
}

declare module 'json-hash/spec/spec-digest' {
  declare module.exports: any;
}

declare module 'json-hash/src/browser' {
  declare module.exports: any;
}

declare module 'json-hash/src/crypto' {
  declare module.exports: any;
}

declare module 'json-hash/src/digest' {
  declare module.exports: any;
}

declare module 'json-hash/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-hash/Gruntfile.js' {
  declare module.exports: $Exports<'json-hash/Gruntfile'>;
}
declare module 'json-hash/lib/browser.js' {
  declare module.exports: $Exports<'json-hash/lib/browser'>;
}
declare module 'json-hash/lib/crypto.js' {
  declare module.exports: $Exports<'json-hash/lib/crypto'>;
}
declare module 'json-hash/lib/digest.js' {
  declare module.exports: $Exports<'json-hash/lib/digest'>;
}
declare module 'json-hash/lib/index.js' {
  declare module.exports: $Exports<'json-hash/lib/index'>;
}
declare module 'json-hash/spec/spec-crypto.js' {
  declare module.exports: $Exports<'json-hash/spec/spec-crypto'>;
}
declare module 'json-hash/spec/spec-digest.js' {
  declare module.exports: $Exports<'json-hash/spec/spec-digest'>;
}
declare module 'json-hash/src/browser.js' {
  declare module.exports: $Exports<'json-hash/src/browser'>;
}
declare module 'json-hash/src/crypto.js' {
  declare module.exports: $Exports<'json-hash/src/crypto'>;
}
declare module 'json-hash/src/digest.js' {
  declare module.exports: $Exports<'json-hash/src/digest'>;
}
declare module 'json-hash/src/index.js' {
  declare module.exports: $Exports<'json-hash/src/index'>;
}
