// flow-typed signature: 6bb487b630af292374ab6bb3f40b1359
// flow-typed version: <<STUB>>/keccak_v^1.3.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keccak'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keccak' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keccak/bindings' {
  declare module.exports: any;
}

declare module 'keccak/js' {
  declare module.exports: any;
}

declare module 'keccak/lib/api/index' {
  declare module.exports: any;
}

declare module 'keccak/lib/api/keccak' {
  declare module.exports: any;
}

declare module 'keccak/lib/api/shake' {
  declare module.exports: any;
}

declare module 'keccak/lib/keccak-state-reference' {
  declare module.exports: any;
}

declare module 'keccak/lib/keccak-state-unroll' {
  declare module.exports: any;
}

declare module 'keccak/lib/keccak' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keccak/bindings.js' {
  declare module.exports: $Exports<'keccak/bindings'>;
}
declare module 'keccak/index' {
  declare module.exports: $Exports<'keccak'>;
}
declare module 'keccak/index.js' {
  declare module.exports: $Exports<'keccak'>;
}
declare module 'keccak/js.js' {
  declare module.exports: $Exports<'keccak/js'>;
}
declare module 'keccak/lib/api/index.js' {
  declare module.exports: $Exports<'keccak/lib/api/index'>;
}
declare module 'keccak/lib/api/keccak.js' {
  declare module.exports: $Exports<'keccak/lib/api/keccak'>;
}
declare module 'keccak/lib/api/shake.js' {
  declare module.exports: $Exports<'keccak/lib/api/shake'>;
}
declare module 'keccak/lib/keccak-state-reference.js' {
  declare module.exports: $Exports<'keccak/lib/keccak-state-reference'>;
}
declare module 'keccak/lib/keccak-state-unroll.js' {
  declare module.exports: $Exports<'keccak/lib/keccak-state-unroll'>;
}
declare module 'keccak/lib/keccak.js' {
  declare module.exports: $Exports<'keccak/lib/keccak'>;
}
