// flow-typed signature: 377d0fe738291a7f6bdb9598f29e2b36
// flow-typed version: <<STUB>>/passwordmeter_v^1.3.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passwordmeter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passwordmeter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passwordmeter/dist/index' {
  declare module.exports: any;
}

declare module 'passwordmeter/dist/index.umd' {
  declare module.exports: any;
}

declare module 'passwordmeter/dist/index.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passwordmeter/dist/index.js' {
  declare module.exports: $Exports<'passwordmeter/dist/index'>;
}
declare module 'passwordmeter/dist/index.umd.js' {
  declare module.exports: $Exports<'passwordmeter/dist/index.umd'>;
}
declare module 'passwordmeter/dist/index.umd.min.js' {
  declare module.exports: $Exports<'passwordmeter/dist/index.umd.min'>;
}
