// flow-typed signature: ae5f70f3ee6022c408b08ba4a0840bce
// flow-typed version: <<STUB>>/re-base_v^3.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-base/dist/bundle' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/src/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/src/components/Container' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/src/components/Message' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/src/components/NewChat' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/src/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/chatapp/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Github/Repos' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Github/UserProfile' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Home' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Main' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/AddNote' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/Notes' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/NotesList' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/Profile' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/components/SearchGithub' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/config/routes' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/app/utils/helpers' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/github-notetaker/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/app/AddItem' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/app/List' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/app/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/Container' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/Message' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/NewChat' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/chatapp/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firebase/todolist - syncState/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/src/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/src/components/Container' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/src/components/Message' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/src/components/NewChat' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/src/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/chatapp/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Github/Repos' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Github/UserProfile' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Home' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Main' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/AddNote' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/Notes' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/NotesList' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/Profile' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/components/SearchGithub' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/config/routes' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/app/utils/helpers' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/github-notetaker/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/todolist/app/AddItem' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/todolist/app/App' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/todolist/app/List' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/todolist/app/rebase' {
  declare module.exports: any;
}

declare module 're-base/examples/firestore/todolist/webpack.config' {
  declare module.exports: any;
}

declare module 're-base/src/lib/bind' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fetch' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsAddToCollection' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsBind' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsGet' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsRemoveBinding' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsRemoveDoc' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsRemoveFromCollection' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsReset' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsSync' {
  declare module.exports: any;
}

declare module 're-base/src/lib/fsUpdateDoc' {
  declare module.exports: any;
}

declare module 're-base/src/lib/post' {
  declare module.exports: any;
}

declare module 're-base/src/lib/push' {
  declare module.exports: any;
}

declare module 're-base/src/lib/remove' {
  declare module.exports: any;
}

declare module 're-base/src/lib/removeBinding' {
  declare module.exports: any;
}

declare module 're-base/src/lib/reset' {
  declare module.exports: any;
}

declare module 're-base/src/lib/sync' {
  declare module.exports: any;
}

declare module 're-base/src/lib/update' {
  declare module.exports: any;
}

declare module 're-base/src/lib/utils' {
  declare module.exports: any;
}

declare module 're-base/src/lib/validators' {
  declare module.exports: any;
}

declare module 're-base/src/rebase' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/config' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyArrayOfObjects' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyArrData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyCollection' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyNestedObjData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyObjData' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/dummyUsers' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/invalidEndpoints' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/invalidOptions' {
  declare module.exports: any;
}

declare module 're-base/tests/fixtures/nestedObjArrResult' {
  declare module.exports: any;
}

declare module 're-base/tests/helpers' {
  declare module.exports: any;
}

declare module 're-base/tests/karma.conf' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/createClass.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/databases.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/addToCollection.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/bindCollection.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/bindDoc.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/get.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/listenToCollection.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/listenToDoc.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/removeDoc.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/removeFromCollection.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/reset.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/syncDoc.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/firestore/updateDoc.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/bindToState.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/fetch.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/listenTo.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/post.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/push.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/remove.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/removeBinding.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/reset.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/serverinfo.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/syncState.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/rtdb/update.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/utils.spec' {
  declare module.exports: any;
}

declare module 're-base/tests/specs/validators.spec' {
  declare module.exports: any;
}

declare module 're-base/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-base/dist/bundle.js' {
  declare module.exports: $Exports<'re-base/dist/bundle'>;
}
declare module 're-base/examples/firebase/chatapp/src/App.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/src/App'>;
}
declare module 're-base/examples/firebase/chatapp/src/components/Container.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/src/components/Container'>;
}
declare module 're-base/examples/firebase/chatapp/src/components/Message.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/src/components/Message'>;
}
declare module 're-base/examples/firebase/chatapp/src/components/NewChat.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/src/components/NewChat'>;
}
declare module 're-base/examples/firebase/chatapp/src/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/src/rebase'>;
}
declare module 're-base/examples/firebase/chatapp/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/chatapp/webpack.config'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/App'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Github/Repos.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Github/Repos'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Github/UserProfile.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Github/UserProfile'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Home.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Home'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Main.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Main'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/AddNote.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Notes/AddNote'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/Notes.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Notes/Notes'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Notes/NotesList.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Notes/NotesList'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/Profile.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/Profile'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/components/SearchGithub.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/components/SearchGithub'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/config/routes.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/config/routes'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/rebase'>;
}
declare module 're-base/examples/firebase/github-notetaker/app/utils/helpers.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/app/utils/helpers'>;
}
declare module 're-base/examples/firebase/github-notetaker/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/github-notetaker/webpack.config'>;
}
declare module 're-base/examples/firebase/todolist - syncState/app/AddItem.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/app/AddItem'>;
}
declare module 're-base/examples/firebase/todolist - syncState/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/app/App'>;
}
declare module 're-base/examples/firebase/todolist - syncState/app/List.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/app/List'>;
}
declare module 're-base/examples/firebase/todolist - syncState/app/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/app/rebase'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/App.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/src/App'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/Container.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/src/components/Container'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/Message.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/src/components/Message'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/components/NewChat.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/src/components/NewChat'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/src/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/src/rebase'>;
}
declare module 're-base/examples/firebase/todolist - syncState/chatapp/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/chatapp/webpack.config'>;
}
declare module 're-base/examples/firebase/todolist - syncState/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firebase/todolist - syncState/webpack.config'>;
}
declare module 're-base/examples/firestore/chatapp/src/App.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/src/App'>;
}
declare module 're-base/examples/firestore/chatapp/src/components/Container.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/src/components/Container'>;
}
declare module 're-base/examples/firestore/chatapp/src/components/Message.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/src/components/Message'>;
}
declare module 're-base/examples/firestore/chatapp/src/components/NewChat.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/src/components/NewChat'>;
}
declare module 're-base/examples/firestore/chatapp/src/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/src/rebase'>;
}
declare module 're-base/examples/firestore/chatapp/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/chatapp/webpack.config'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/App'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Github/Repos.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Github/Repos'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Github/UserProfile.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Github/UserProfile'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Home.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Home'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Main.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Main'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/AddNote.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Notes/AddNote'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/Notes.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Notes/Notes'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Notes/NotesList.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Notes/NotesList'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/Profile.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/Profile'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/components/SearchGithub.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/components/SearchGithub'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/config/routes.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/config/routes'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/rebase'>;
}
declare module 're-base/examples/firestore/github-notetaker/app/utils/helpers.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/app/utils/helpers'>;
}
declare module 're-base/examples/firestore/github-notetaker/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/github-notetaker/webpack.config'>;
}
declare module 're-base/examples/firestore/todolist/app/AddItem.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/todolist/app/AddItem'>;
}
declare module 're-base/examples/firestore/todolist/app/App.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/todolist/app/App'>;
}
declare module 're-base/examples/firestore/todolist/app/List.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/todolist/app/List'>;
}
declare module 're-base/examples/firestore/todolist/app/rebase.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/todolist/app/rebase'>;
}
declare module 're-base/examples/firestore/todolist/webpack.config.js' {
  declare module.exports: $Exports<'re-base/examples/firestore/todolist/webpack.config'>;
}
declare module 're-base/index' {
  declare module.exports: $Exports<'re-base'>;
}
declare module 're-base/index.js' {
  declare module.exports: $Exports<'re-base'>;
}
declare module 're-base/src/lib/bind.js' {
  declare module.exports: $Exports<'re-base/src/lib/bind'>;
}
declare module 're-base/src/lib/fetch.js' {
  declare module.exports: $Exports<'re-base/src/lib/fetch'>;
}
declare module 're-base/src/lib/fsAddToCollection.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsAddToCollection'>;
}
declare module 're-base/src/lib/fsBind.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsBind'>;
}
declare module 're-base/src/lib/fsGet.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsGet'>;
}
declare module 're-base/src/lib/fsRemoveBinding.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsRemoveBinding'>;
}
declare module 're-base/src/lib/fsRemoveDoc.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsRemoveDoc'>;
}
declare module 're-base/src/lib/fsRemoveFromCollection.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsRemoveFromCollection'>;
}
declare module 're-base/src/lib/fsReset.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsReset'>;
}
declare module 're-base/src/lib/fsSync.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsSync'>;
}
declare module 're-base/src/lib/fsUpdateDoc.js' {
  declare module.exports: $Exports<'re-base/src/lib/fsUpdateDoc'>;
}
declare module 're-base/src/lib/post.js' {
  declare module.exports: $Exports<'re-base/src/lib/post'>;
}
declare module 're-base/src/lib/push.js' {
  declare module.exports: $Exports<'re-base/src/lib/push'>;
}
declare module 're-base/src/lib/remove.js' {
  declare module.exports: $Exports<'re-base/src/lib/remove'>;
}
declare module 're-base/src/lib/removeBinding.js' {
  declare module.exports: $Exports<'re-base/src/lib/removeBinding'>;
}
declare module 're-base/src/lib/reset.js' {
  declare module.exports: $Exports<'re-base/src/lib/reset'>;
}
declare module 're-base/src/lib/sync.js' {
  declare module.exports: $Exports<'re-base/src/lib/sync'>;
}
declare module 're-base/src/lib/update.js' {
  declare module.exports: $Exports<'re-base/src/lib/update'>;
}
declare module 're-base/src/lib/utils.js' {
  declare module.exports: $Exports<'re-base/src/lib/utils'>;
}
declare module 're-base/src/lib/validators.js' {
  declare module.exports: $Exports<'re-base/src/lib/validators'>;
}
declare module 're-base/src/rebase.js' {
  declare module.exports: $Exports<'re-base/src/rebase'>;
}
declare module 're-base/tests/fixtures/config.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/config'>;
}
declare module 're-base/tests/fixtures/dummyArrayOfObjects.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyArrayOfObjects'>;
}
declare module 're-base/tests/fixtures/dummyArrData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyArrData'>;
}
declare module 're-base/tests/fixtures/dummyCollection.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyCollection'>;
}
declare module 're-base/tests/fixtures/dummyNestedObjData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyNestedObjData'>;
}
declare module 're-base/tests/fixtures/dummyObjData.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyObjData'>;
}
declare module 're-base/tests/fixtures/dummyUsers.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/dummyUsers'>;
}
declare module 're-base/tests/fixtures/invalidEndpoints.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/invalidEndpoints'>;
}
declare module 're-base/tests/fixtures/invalidOptions.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/invalidOptions'>;
}
declare module 're-base/tests/fixtures/nestedObjArrResult.js' {
  declare module.exports: $Exports<'re-base/tests/fixtures/nestedObjArrResult'>;
}
declare module 're-base/tests/helpers.js' {
  declare module.exports: $Exports<'re-base/tests/helpers'>;
}
declare module 're-base/tests/karma.conf.js' {
  declare module.exports: $Exports<'re-base/tests/karma.conf'>;
}
declare module 're-base/tests/specs/createClass.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/createClass.spec'>;
}
declare module 're-base/tests/specs/databases.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/databases.spec'>;
}
declare module 're-base/tests/specs/firestore/addToCollection.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/addToCollection.spec'>;
}
declare module 're-base/tests/specs/firestore/bindCollection.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/bindCollection.spec'>;
}
declare module 're-base/tests/specs/firestore/bindDoc.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/bindDoc.spec'>;
}
declare module 're-base/tests/specs/firestore/get.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/get.spec'>;
}
declare module 're-base/tests/specs/firestore/listenToCollection.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/listenToCollection.spec'>;
}
declare module 're-base/tests/specs/firestore/listenToDoc.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/listenToDoc.spec'>;
}
declare module 're-base/tests/specs/firestore/removeDoc.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/removeDoc.spec'>;
}
declare module 're-base/tests/specs/firestore/removeFromCollection.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/removeFromCollection.spec'>;
}
declare module 're-base/tests/specs/firestore/reset.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/reset.spec'>;
}
declare module 're-base/tests/specs/firestore/syncDoc.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/syncDoc.spec'>;
}
declare module 're-base/tests/specs/firestore/updateDoc.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/firestore/updateDoc.spec'>;
}
declare module 're-base/tests/specs/rtdb/bindToState.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/bindToState.spec'>;
}
declare module 're-base/tests/specs/rtdb/fetch.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/fetch.spec'>;
}
declare module 're-base/tests/specs/rtdb/listenTo.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/listenTo.spec'>;
}
declare module 're-base/tests/specs/rtdb/post.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/post.spec'>;
}
declare module 're-base/tests/specs/rtdb/push.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/push.spec'>;
}
declare module 're-base/tests/specs/rtdb/remove.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/remove.spec'>;
}
declare module 're-base/tests/specs/rtdb/removeBinding.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/removeBinding.spec'>;
}
declare module 're-base/tests/specs/rtdb/reset.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/reset.spec'>;
}
declare module 're-base/tests/specs/rtdb/serverinfo.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/serverinfo.spec'>;
}
declare module 're-base/tests/specs/rtdb/syncState.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/syncState.spec'>;
}
declare module 're-base/tests/specs/rtdb/update.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/rtdb/update.spec'>;
}
declare module 're-base/tests/specs/utils.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/utils.spec'>;
}
declare module 're-base/tests/specs/validators.spec.js' {
  declare module.exports: $Exports<'re-base/tests/specs/validators.spec'>;
}
declare module 're-base/webpack.config.js' {
  declare module.exports: $Exports<'re-base/webpack.config'>;
}
