// flow-typed signature: e70808297eb2b32b36c319bf5f0b904d
// flow-typed version: <<STUB>>/react-toastify_v^4.0.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/dist/ReactToastify' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/components/Transitions' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/index' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/toaster' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/constant' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/EventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/lib/utils/propValidator' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/EventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/propValidator' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/src/__tests__/toaster' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/Toast' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/ToastContainer' {
  declare module.exports: any;
}

declare module 'react-toastify/src/components/Transitions' {
  declare module.exports: any;
}

declare module 'react-toastify/src/index' {
  declare module.exports: any;
}

declare module 'react-toastify/src/toaster' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/constant' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/cssTransition' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/EventManager' {
  declare module.exports: any;
}

declare module 'react-toastify/src/utils/propValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/dist/ReactToastify.js' {
  declare module.exports: $Exports<'react-toastify/dist/ReactToastify'>;
}
declare module 'react-toastify/lib/components/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/CloseButton'>;
}
declare module 'react-toastify/lib/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/ProgressBar'>;
}
declare module 'react-toastify/lib/components/Toast.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/Toast'>;
}
declare module 'react-toastify/lib/components/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/ToastContainer'>;
}
declare module 'react-toastify/lib/components/Transitions.js' {
  declare module.exports: $Exports<'react-toastify/lib/components/Transitions'>;
}
declare module 'react-toastify/lib/index.js' {
  declare module.exports: $Exports<'react-toastify/lib/index'>;
}
declare module 'react-toastify/lib/toaster.js' {
  declare module.exports: $Exports<'react-toastify/lib/toaster'>;
}
declare module 'react-toastify/lib/utils/constant.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/constant'>;
}
declare module 'react-toastify/lib/utils/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/cssTransition'>;
}
declare module 'react-toastify/lib/utils/EventManager.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/EventManager'>;
}
declare module 'react-toastify/lib/utils/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/lib/utils/propValidator'>;
}
declare module 'react-toastify/src/__tests__/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/CloseButton'>;
}
declare module 'react-toastify/src/__tests__/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/cssTransition'>;
}
declare module 'react-toastify/src/__tests__/EventManager.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/EventManager'>;
}
declare module 'react-toastify/src/__tests__/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/ProgressBar'>;
}
declare module 'react-toastify/src/__tests__/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/propValidator'>;
}
declare module 'react-toastify/src/__tests__/Toast.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/Toast'>;
}
declare module 'react-toastify/src/__tests__/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/ToastContainer'>;
}
declare module 'react-toastify/src/__tests__/toaster.js' {
  declare module.exports: $Exports<'react-toastify/src/__tests__/toaster'>;
}
declare module 'react-toastify/src/components/CloseButton.js' {
  declare module.exports: $Exports<'react-toastify/src/components/CloseButton'>;
}
declare module 'react-toastify/src/components/ProgressBar.js' {
  declare module.exports: $Exports<'react-toastify/src/components/ProgressBar'>;
}
declare module 'react-toastify/src/components/Toast.js' {
  declare module.exports: $Exports<'react-toastify/src/components/Toast'>;
}
declare module 'react-toastify/src/components/ToastContainer.js' {
  declare module.exports: $Exports<'react-toastify/src/components/ToastContainer'>;
}
declare module 'react-toastify/src/components/Transitions.js' {
  declare module.exports: $Exports<'react-toastify/src/components/Transitions'>;
}
declare module 'react-toastify/src/index.js' {
  declare module.exports: $Exports<'react-toastify/src/index'>;
}
declare module 'react-toastify/src/toaster.js' {
  declare module.exports: $Exports<'react-toastify/src/toaster'>;
}
declare module 'react-toastify/src/utils/constant.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/constant'>;
}
declare module 'react-toastify/src/utils/cssTransition.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/cssTransition'>;
}
declare module 'react-toastify/src/utils/EventManager.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/EventManager'>;
}
declare module 'react-toastify/src/utils/propValidator.js' {
  declare module.exports: $Exports<'react-toastify/src/utils/propValidator'>;
}
