// flow-typed signature: 23fb0cdd372c772891b8446bb9a3e51f
// flow-typed version: <<STUB>>/react-alert_v^2.4.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-alert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-alert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-alert/dist/alert-container/AlertContainer' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert-container/Container' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert-container/index' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/Alert' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/AlertMessage' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/Close' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/Icon' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/index' {
  declare module.exports: any;
}

declare module 'react-alert/dist/alert/Message' {
  declare module.exports: any;
}

declare module 'react-alert/dist/index' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert-container/AlertContainer' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert-container/AlertContainer.spec' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert-container/Container' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert-container/index' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/Alert' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/AlertMessage' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/AlertMessage.spec' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/Close' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/Icon' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/index' {
  declare module.exports: any;
}

declare module 'react-alert/src/alert/Message' {
  declare module.exports: any;
}

declare module 'react-alert/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-alert/dist/alert-container/AlertContainer.js' {
  declare module.exports: $Exports<'react-alert/dist/alert-container/AlertContainer'>;
}
declare module 'react-alert/dist/alert-container/Container.js' {
  declare module.exports: $Exports<'react-alert/dist/alert-container/Container'>;
}
declare module 'react-alert/dist/alert-container/index.js' {
  declare module.exports: $Exports<'react-alert/dist/alert-container/index'>;
}
declare module 'react-alert/dist/alert/Alert.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/Alert'>;
}
declare module 'react-alert/dist/alert/AlertMessage.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/AlertMessage'>;
}
declare module 'react-alert/dist/alert/Close.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/Close'>;
}
declare module 'react-alert/dist/alert/Icon.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/Icon'>;
}
declare module 'react-alert/dist/alert/index.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/index'>;
}
declare module 'react-alert/dist/alert/Message.js' {
  declare module.exports: $Exports<'react-alert/dist/alert/Message'>;
}
declare module 'react-alert/dist/index.js' {
  declare module.exports: $Exports<'react-alert/dist/index'>;
}
declare module 'react-alert/src/alert-container/AlertContainer.js' {
  declare module.exports: $Exports<'react-alert/src/alert-container/AlertContainer'>;
}
declare module 'react-alert/src/alert-container/AlertContainer.spec.js' {
  declare module.exports: $Exports<'react-alert/src/alert-container/AlertContainer.spec'>;
}
declare module 'react-alert/src/alert-container/Container.js' {
  declare module.exports: $Exports<'react-alert/src/alert-container/Container'>;
}
declare module 'react-alert/src/alert-container/index.js' {
  declare module.exports: $Exports<'react-alert/src/alert-container/index'>;
}
declare module 'react-alert/src/alert/Alert.js' {
  declare module.exports: $Exports<'react-alert/src/alert/Alert'>;
}
declare module 'react-alert/src/alert/AlertMessage.js' {
  declare module.exports: $Exports<'react-alert/src/alert/AlertMessage'>;
}
declare module 'react-alert/src/alert/AlertMessage.spec.js' {
  declare module.exports: $Exports<'react-alert/src/alert/AlertMessage.spec'>;
}
declare module 'react-alert/src/alert/Close.js' {
  declare module.exports: $Exports<'react-alert/src/alert/Close'>;
}
declare module 'react-alert/src/alert/Icon.js' {
  declare module.exports: $Exports<'react-alert/src/alert/Icon'>;
}
declare module 'react-alert/src/alert/index.js' {
  declare module.exports: $Exports<'react-alert/src/alert/index'>;
}
declare module 'react-alert/src/alert/Message.js' {
  declare module.exports: $Exports<'react-alert/src/alert/Message'>;
}
declare module 'react-alert/src/index.js' {
  declare module.exports: $Exports<'react-alert/src/index'>;
}
