// flow-typed signature: e54ac7d81313c71c17996710b7d7b527
// flow-typed version: <<STUB>>/react-easy-chart_v^0.3.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-easy-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-easy-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-easy-chart/lib/area-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/bar-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/legend/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/legend/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultAxisStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultColors' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/line-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/pie-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/pie-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/scatterplot-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/scatterplot-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/lib/shared' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/area-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/bar-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/legend/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/legend/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultAxisStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultColors' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultStyles' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/line-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/pie-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/pie-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/scatterplot-chart/hybrid/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/scatterplot-chart/static/index' {
  declare module.exports: any;
}

declare module 'react-easy-chart/modules/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-easy-chart/lib/area-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/area-chart/index'>;
}
declare module 'react-easy-chart/lib/bar-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/bar-chart/index'>;
}
declare module 'react-easy-chart/lib/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/index'>;
}
declare module 'react-easy-chart/lib/legend/defaultStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/legend/defaultStyles'>;
}
declare module 'react-easy-chart/lib/legend/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/legend/index'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/index'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/LineChart/common'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultAxisStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultAxisStyles'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultColors.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultColors'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/LineChart/common/defaultStyles'>;
}
declare module 'react-easy-chart/lib/line-chart/hybrid/LineChart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/hybrid/LineChart/index'>;
}
declare module 'react-easy-chart/lib/line-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/index'>;
}
declare module 'react-easy-chart/lib/line-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/line-chart/static/index'>;
}
declare module 'react-easy-chart/lib/pie-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/pie-chart/hybrid/index'>;
}
declare module 'react-easy-chart/lib/pie-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/pie-chart/static/index'>;
}
declare module 'react-easy-chart/lib/scatterplot-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/scatterplot-chart/hybrid/index'>;
}
declare module 'react-easy-chart/lib/scatterplot-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/scatterplot-chart/static/index'>;
}
declare module 'react-easy-chart/lib/shared.js' {
  declare module.exports: $Exports<'react-easy-chart/lib/shared'>;
}
declare module 'react-easy-chart/modules/area-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/area-chart/index'>;
}
declare module 'react-easy-chart/modules/bar-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/bar-chart/index'>;
}
declare module 'react-easy-chart/modules/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/index'>;
}
declare module 'react-easy-chart/modules/legend/defaultStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/legend/defaultStyles'>;
}
declare module 'react-easy-chart/modules/legend/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/legend/index'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/index'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/LineChart/common'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultAxisStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultAxisStyles'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultColors.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultColors'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultStyles.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/LineChart/common/defaultStyles'>;
}
declare module 'react-easy-chart/modules/line-chart/hybrid/LineChart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/hybrid/LineChart/index'>;
}
declare module 'react-easy-chart/modules/line-chart/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/index'>;
}
declare module 'react-easy-chart/modules/line-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/line-chart/static/index'>;
}
declare module 'react-easy-chart/modules/pie-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/pie-chart/hybrid/index'>;
}
declare module 'react-easy-chart/modules/pie-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/pie-chart/static/index'>;
}
declare module 'react-easy-chart/modules/scatterplot-chart/hybrid/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/scatterplot-chart/hybrid/index'>;
}
declare module 'react-easy-chart/modules/scatterplot-chart/static/index.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/scatterplot-chart/static/index'>;
}
declare module 'react-easy-chart/modules/shared.js' {
  declare module.exports: $Exports<'react-easy-chart/modules/shared'>;
}
