// flow-typed signature: b52f5d16394fee4dcd2ea3e03a8c8362
// flow-typed version: <<STUB>>/react-avatar_v^2.5.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-avatar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-avatar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-avatar/build/demo' {
  declare module.exports: any;
}

declare module 'react-avatar/bundle' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/demo' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/index' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Facebook' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Google' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Gravatar' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Icon' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Skype' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Src' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Twitter' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Value' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/sources/Vkontakte' {
  declare module.exports: any;
}

declare module 'react-avatar/lib/utils' {
  declare module.exports: any;
}

declare module 'react-avatar/src/demo' {
  declare module.exports: any;
}

declare module 'react-avatar/src/index' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Facebook' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Google' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Gravatar' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Icon' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Skype' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Src' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Twitter' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Value' {
  declare module.exports: any;
}

declare module 'react-avatar/src/sources/Vkontakte' {
  declare module.exports: any;
}

declare module 'react-avatar/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-avatar/build/demo.js' {
  declare module.exports: $Exports<'react-avatar/build/demo'>;
}
declare module 'react-avatar/bundle.js' {
  declare module.exports: $Exports<'react-avatar/bundle'>;
}
declare module 'react-avatar/lib/demo.js' {
  declare module.exports: $Exports<'react-avatar/lib/demo'>;
}
declare module 'react-avatar/lib/index.js' {
  declare module.exports: $Exports<'react-avatar/lib/index'>;
}
declare module 'react-avatar/lib/sources/Facebook.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Facebook'>;
}
declare module 'react-avatar/lib/sources/Google.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Google'>;
}
declare module 'react-avatar/lib/sources/Gravatar.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Gravatar'>;
}
declare module 'react-avatar/lib/sources/Icon.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Icon'>;
}
declare module 'react-avatar/lib/sources/Skype.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Skype'>;
}
declare module 'react-avatar/lib/sources/Src.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Src'>;
}
declare module 'react-avatar/lib/sources/Twitter.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Twitter'>;
}
declare module 'react-avatar/lib/sources/Value.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Value'>;
}
declare module 'react-avatar/lib/sources/Vkontakte.js' {
  declare module.exports: $Exports<'react-avatar/lib/sources/Vkontakte'>;
}
declare module 'react-avatar/lib/utils.js' {
  declare module.exports: $Exports<'react-avatar/lib/utils'>;
}
declare module 'react-avatar/src/demo.js' {
  declare module.exports: $Exports<'react-avatar/src/demo'>;
}
declare module 'react-avatar/src/index.js' {
  declare module.exports: $Exports<'react-avatar/src/index'>;
}
declare module 'react-avatar/src/sources/Facebook.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Facebook'>;
}
declare module 'react-avatar/src/sources/Google.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Google'>;
}
declare module 'react-avatar/src/sources/Gravatar.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Gravatar'>;
}
declare module 'react-avatar/src/sources/Icon.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Icon'>;
}
declare module 'react-avatar/src/sources/Skype.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Skype'>;
}
declare module 'react-avatar/src/sources/Src.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Src'>;
}
declare module 'react-avatar/src/sources/Twitter.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Twitter'>;
}
declare module 'react-avatar/src/sources/Value.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Value'>;
}
declare module 'react-avatar/src/sources/Vkontakte.js' {
  declare module.exports: $Exports<'react-avatar/src/sources/Vkontakte'>;
}
declare module 'react-avatar/src/utils.js' {
  declare module.exports: $Exports<'react-avatar/src/utils'>;
}
