// flow-typed signature: 5f6d847a31a6ed0d5250b1a0c587a1e8
// flow-typed version: <<STUB>>/react-awesome-modal_v^2.0.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-awesome-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-awesome-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-awesome-modal/lib/effect/fadeInDown' {
  declare module.exports: any;
}

declare module 'react-awesome-modal/lib/effect/fadeInLeft' {
  declare module.exports: any;
}

declare module 'react-awesome-modal/lib/effect/fadeInRight' {
  declare module.exports: any;
}

declare module 'react-awesome-modal/lib/effect/fadeInUp' {
  declare module.exports: any;
}

declare module 'react-awesome-modal/lib/index' {
  declare module.exports: any;
}

declare module 'react-awesome-modal/lib/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-awesome-modal/lib/effect/fadeInDown.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/effect/fadeInDown'>;
}
declare module 'react-awesome-modal/lib/effect/fadeInLeft.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/effect/fadeInLeft'>;
}
declare module 'react-awesome-modal/lib/effect/fadeInRight.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/effect/fadeInRight'>;
}
declare module 'react-awesome-modal/lib/effect/fadeInUp.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/effect/fadeInUp'>;
}
declare module 'react-awesome-modal/lib/index.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/index'>;
}
declare module 'react-awesome-modal/lib/style.js' {
  declare module.exports: $Exports<'react-awesome-modal/lib/style'>;
}
