// flow-typed signature: 581b978886a60ab2fa9b677c78991c58
// flow-typed version: <<STUB>>/react-faux-dom_v^4.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-faux-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-faux-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-faux-dom/dist/ReactFauxDOM.min' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/Element' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/ReactFauxDOM' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/assign' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/camelCase' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/isString' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/isUndefined' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/mapValues' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/utils/styleCamelCase' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/Window' {
  declare module.exports: any;
}

declare module 'react-faux-dom/lib/withFauxDOM' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-faux-dom/dist/ReactFauxDOM.min.js' {
  declare module.exports: $Exports<'react-faux-dom/dist/ReactFauxDOM.min'>;
}
declare module 'react-faux-dom/lib/Element.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/Element'>;
}
declare module 'react-faux-dom/lib/ReactFauxDOM.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/ReactFauxDOM'>;
}
declare module 'react-faux-dom/lib/utils/assign.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/assign'>;
}
declare module 'react-faux-dom/lib/utils/camelCase.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/camelCase'>;
}
declare module 'react-faux-dom/lib/utils/isString.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/isString'>;
}
declare module 'react-faux-dom/lib/utils/isUndefined.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/isUndefined'>;
}
declare module 'react-faux-dom/lib/utils/mapValues.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/mapValues'>;
}
declare module 'react-faux-dom/lib/utils/styleCamelCase.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/utils/styleCamelCase'>;
}
declare module 'react-faux-dom/lib/Window.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/Window'>;
}
declare module 'react-faux-dom/lib/withFauxDOM.js' {
  declare module.exports: $Exports<'react-faux-dom/lib/withFauxDOM'>;
}
