// flow-typed signature: 1c8772ba00f84d7b7d0fe275575dedab
// flow-typed version: <<STUB>>/react-page-visibility_v^3.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-page-visibility'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-page-visibility' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-page-visibility/dist/index.es5' {
  declare module.exports: any;
}

declare module 'react-page-visibility/dist/index' {
  declare module.exports: any;
}

declare module 'react-page-visibility/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-page-visibility/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-page-visibility/dist/index.es5.js' {
  declare module.exports: $Exports<'react-page-visibility/dist/index.es5'>;
}
declare module 'react-page-visibility/dist/index.js' {
  declare module.exports: $Exports<'react-page-visibility/dist/index'>;
}
declare module 'react-page-visibility/dist/index.umd.js' {
  declare module.exports: $Exports<'react-page-visibility/dist/index.umd'>;
}
declare module 'react-page-visibility/src/index.js' {
  declare module.exports: $Exports<'react-page-visibility/src/index'>;
}
