// flow-typed signature: ed1d87072faccba739279c1329b3caaf
// flow-typed version: <<STUB>>/react-donut-chart_v^1.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-donut-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-donut-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-donut-chart/lib/dist/ArcPath' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/dist/Arcs' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/dist/DonutChart' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/dist/DonutInnerText' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/dist/Legend' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/dist/LegendItem' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/ArcPath' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/Arcs' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/DonutChart' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/DonutInnerText' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/Legend' {
  declare module.exports: any;
}

declare module 'react-donut-chart/lib/src/LegendItem' {
  declare module.exports: any;
}

declare module 'react-donut-chart/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-donut-chart/index' {
  declare module.exports: $Exports<'react-donut-chart'>;
}
declare module 'react-donut-chart/index.js' {
  declare module.exports: $Exports<'react-donut-chart'>;
}
declare module 'react-donut-chart/lib/dist/ArcPath.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/ArcPath'>;
}
declare module 'react-donut-chart/lib/dist/Arcs.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/Arcs'>;
}
declare module 'react-donut-chart/lib/dist/DonutChart.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/DonutChart'>;
}
declare module 'react-donut-chart/lib/dist/DonutInnerText.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/DonutInnerText'>;
}
declare module 'react-donut-chart/lib/dist/Legend.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/Legend'>;
}
declare module 'react-donut-chart/lib/dist/LegendItem.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/dist/LegendItem'>;
}
declare module 'react-donut-chart/lib/src/ArcPath.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/ArcPath'>;
}
declare module 'react-donut-chart/lib/src/Arcs.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/Arcs'>;
}
declare module 'react-donut-chart/lib/src/DonutChart.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/DonutChart'>;
}
declare module 'react-donut-chart/lib/src/DonutInnerText.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/DonutInnerText'>;
}
declare module 'react-donut-chart/lib/src/Legend.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/Legend'>;
}
declare module 'react-donut-chart/lib/src/LegendItem.js' {
  declare module.exports: $Exports<'react-donut-chart/lib/src/LegendItem'>;
}
declare module 'react-donut-chart/webpack.config.js' {
  declare module.exports: $Exports<'react-donut-chart/webpack.config'>;
}
