// flow-typed signature: 74e7ab9a2cab01aba4e97c5fb6c17461
// flow-typed version: <<STUB>>/socicon_v^3.0.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socicon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socicon' {
  declare module.exports: any;
}
