// flow-typed signature: b1e948f9f701214099810a094c97a54d
// flow-typed version: <<STUB>>/styled-reset_v^0.1.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-reset/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-reset/lib/index.js' {
  declare module.exports: $Exports<'styled-reset/lib/index'>;
}
