// flow-typed signature: aac4b9c9f2a8932064d7bff1aa803efd
// flow-typed version: <<STUB>>/treis_v^2.5.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'treis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'treis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'treis/lib/get-fn-args' {
  declare module.exports: any;
}

declare module 'treis/lib/get-fn-name' {
  declare module.exports: any;
}

declare module 'treis/lib/identity' {
  declare module.exports: any;
}

declare module 'treis/lib/str2color' {
  declare module.exports: any;
}

declare module 'treis/lib/utils-browser' {
  declare module.exports: any;
}

declare module 'treis/lib/utils' {
  declare module.exports: any;
}

declare module 'treis/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'treis/index' {
  declare module.exports: $Exports<'treis'>;
}
declare module 'treis/index.js' {
  declare module.exports: $Exports<'treis'>;
}
declare module 'treis/lib/get-fn-args.js' {
  declare module.exports: $Exports<'treis/lib/get-fn-args'>;
}
declare module 'treis/lib/get-fn-name.js' {
  declare module.exports: $Exports<'treis/lib/get-fn-name'>;
}
declare module 'treis/lib/identity.js' {
  declare module.exports: $Exports<'treis/lib/identity'>;
}
declare module 'treis/lib/str2color.js' {
  declare module.exports: $Exports<'treis/lib/str2color'>;
}
declare module 'treis/lib/utils-browser.js' {
  declare module.exports: $Exports<'treis/lib/utils-browser'>;
}
declare module 'treis/lib/utils.js' {
  declare module.exports: $Exports<'treis/lib/utils'>;
}
declare module 'treis/test.js' {
  declare module.exports: $Exports<'treis/test'>;
}
